CREATE TABLE [dbo].[dataobekt] (
  [kodobk] [int] NOT NULL,
  [GKT] [float] NULL CONSTRAINT [DF_dataobekt_GKT] DEFAULT (0),
  [GKV] [float] NULL CONSTRAINT [DF_dataobekt_GKV] DEFAULT (0),
  [ST] [int] NULL,
  [SV] [int] NULL,
  [SYMT] [float] NULL CONSTRAINT [DF_dataobekt_SYMT] DEFAULT (0),
  [SYMV] [float] NULL CONSTRAINT [DF_dataobekt_SYMV] DEFAULT (0),
  [PERT] [float] NULL CONSTRAINT [DF_dataobekt_PERT] DEFAULT (0),
  [PERV] [float] NULL CONSTRAINT [DF_dataobekt_PERV] DEFAULT (0),
  [PGKT] [float] NULL CONSTRAINT [DF_dataobekt_PGKT] DEFAULT (0),
  [PGKV] [float] NULL CONSTRAINT [DF_dataobekt_PGKV] DEFAULT (0),
  [SYMK] [float] NULL CONSTRAINT [DF_dataobekt_SYMK] DEFAULT (0),
  [SYMGV] [float] NULL CONSTRAINT [DF_dataobekt_SYMGV] DEFAULT (0),
  [TVN] [float] NULL,
  [KDO] [float] NULL,
  [TS] [float] NULL,
  [DGV] [float] NULL,
  [TGV] [float] NULL,
  [DATAN] [datetime] NULL,
  [DATAK] [datetime] NULL,
  [symtnds] [float] NULL CONSTRAINT [DF_dataobekt_symtnds] DEFAULT (0),
  [symvnds] [float] NULL CONSTRAINT [DF_dataobekt_symvnds] DEFAULT (0),
  [rastarift] [float] NULL CONSTRAINT [DF_dataobekt_rastarift] DEFAULT (0),
  [rastarifv] [float] NULL CONSTRAINT [DF_dataobekt_rastarifv] DEFAULT (0),
  [KCO] [float] NULL,
  [kybv] [float] NULL CONSTRAINT [DF_dataobekt_kybv] DEFAULT (0),
  [kybk] [float] NULL CONSTRAINT [DF_dataobekt_kybk] DEFAULT (0),
  [symh] [float] NULL CONSTRAINT [DF_dataobekt_symh] DEFAULT (0),
  [symkk] [float] NULL CONSTRAINT [DF_dataobekt_symkk] DEFAULT (0),
  [symhnds] [float] NULL CONSTRAINT [DF_dataobekt_symhnds] DEFAULT (0),
  [symknds] [float] NULL CONSTRAINT [DF_dataobekt_symknds] DEFAULT (0),
  [symhs] [float] NULL CONSTRAINT [DF_dataobekt_symhs] DEFAULT (0),
  [symks] [float] NULL CONSTRAINT [DF_dataobekt_symks] DEFAULT (0),
  [perh] [float] NULL CONSTRAINT [DF_dataobekt_perh] DEFAULT (0),
  [perk] [float] NULL CONSTRAINT [DF_dataobekt_perk] DEFAULT (0),
  [pkybv] [float] NULL CONSTRAINT [DF_dataobekt_pkybv] DEFAULT (0),
  [pkybk] [float] NULL CONSTRAINT [DF_dataobekt_pkybk] DEFAULT (0),
  [rastarifk] [float] NULL CONSTRAINT [DF_dataobekt_rastarifk] DEFAULT (0),
  [pertnds] [float] NULL CONSTRAINT [DF_dataobekt_pertnds] DEFAULT (0),
  [pervnds] [float] NULL CONSTRAINT [DF_dataobekt_pervnds] DEFAULT (0),
  [perhnds] [float] NULL CONSTRAINT [DF_dataobekt_perhnds] DEFAULT (0),
  [perknds] [float] NULL CONSTRAINT [DF_dataobekt_perknds] DEFAULT (0),
  [lsymt] [float] NULL CONSTRAINT [DF_dataobekt_lsymt] DEFAULT (0),
  [lgkt] [float] NULL CONSTRAINT [DF_dataobekt_lgkt] DEFAULT (0),
  [lsymv] [float] NULL CONSTRAINT [DF_dataobekt_lsymv] DEFAULT (0),
  [lgkv] [float] NULL CONSTRAINT [DF_dataobekt_lgkv] DEFAULT (0),
  [lsymh] [float] NULL CONSTRAINT [DF_dataobekt_lsymh] DEFAULT (0),
  [lkybv] [float] NULL CONSTRAINT [DF_dataobekt_lkybv] DEFAULT (0),
  [lsymkk] [float] NULL CONSTRAINT [DF_dataobekt_lsymkk] DEFAULT (0),
  [lkybk] [float] NULL CONSTRAINT [DF_dataobekt_lkybk] DEFAULT (0),
  [pt] [int] NULL,
  [pv] [int] NULL,
  [rastarifg] [float] NULL CONSTRAINT [DF_dataobekt_rastarifg] DEFAULT (0),
  [kybg] [float] NULL CONSTRAINT [DF_dataobekt_kybg] DEFAULT (0),
  [symg] [float] NULL CONSTRAINT [DF_dataobekt_symg] DEFAULT (0),
  [symgnds] [float] NULL CONSTRAINT [DF_dataobekt_symgnds] DEFAULT (0),
  [symgs] [float] NULL CONSTRAINT [DF_dataobekt_symgs] DEFAULT (0),
  [perg] [float] NULL CONSTRAINT [DF_dataobekt_perg] DEFAULT (0),
  [pkybg] [float] NULL CONSTRAINT [DF_dataobekt_pkybg] DEFAULT (0),
  [pergnds] [float] NULL CONSTRAINT [DF_dataobekt_pergnds] DEFAULT (0),
  [pg] [int] NULL,
  [lsymg] [float] NULL CONSTRAINT [DF_dataobekt_lsymg] DEFAULT (0),
  [lkybg] [float] NULL CONSTRAINT [DF_dataobekt_lkybg] DEFAULT (0)
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[dataobekt] WITH NOCHECK
  ADD CONSTRAINT [FK_dataobekt_obekt] FOREIGN KEY ([kodobk]) REFERENCES [dbo].[obekt] ([kodobk]) ON DELETE CASCADE ON UPDATE CASCADE
GO

DECLARE @value SQL_VARIANT = CAST(N'' AS nvarchar(1))
EXEC sys.sp_addextendedproperty N'MS_Description', @value, 'SCHEMA', N'dbo', 'TABLE', N'dataobekt', 'COLUMN', N'PGKT'
GO