CREATE TABLE [dbo].[datakvart] (
  [KODKV] [int] NOT NULL,
  [KDO] [float] NULL,
  [TV] [float] NULL,
  [TNV] [float] NULL,
  [KDKO] [float] NULL,
  [TKO] [float] NULL,
  [TKNV] [float] NULL,
  [KDBO] [float] NULL,
  [TBO] [float] NULL,
  [TBNV] [float] NULL,
  [KCO] [float] NULL,
  [KDV] [float] NULL,
  [KCG] [float] NULL,
  [TGV] [float] NULL,
  [KDKV] [float] NULL,
  [TGKV] [float] NULL,
  [KDBV] [float] NULL,
  [TBGV] [float] NULL,
  [GKT] [float] NULL CONSTRAINT [DF_datakvart_GKT] DEFAULT (0),
  [GKKT] [float] NULL CONSTRAINT [DF_datakvart_GKKT] DEFAULT (0),
  [GBKT] [float] NULL CONSTRAINT [DF_datakvart_GBKT] DEFAULT (0),
  [GKV] [float] NULL CONSTRAINT [DF_datakvart_GKV] DEFAULT (0),
  [GKKV] [float] NULL CONSTRAINT [DF_datakvart_GKKV] DEFAULT (0),
  [GBKV] [float] NULL CONSTRAINT [DF_datakvart_GBKV0] DEFAULT (0),
  [DATAN] [datetime] NULL,
  [DATAK] [datetime] NULL,
  [pt] [int] NULL,
  [pv] [int] NULL,
  [normativ] [decimal](18, 5) NULL,
  [normativgv] [decimal](18, 5) NULL
)
ON [PRIMARY]
GO