CREATE TABLE [dbo].[datatoplivo] (
  [KODKOT] [int] NOT NULL,
  [ROTG] [float] NULL,
  [RGVG] [float] NULL,
  [PSG] [float] NULL,
  [VYRG] [float] NULL,
  [NORMAG] [float] NULL,
  [KOLG] [float] NULL,
  [TUTG] [float] NULL,
  [PRGR] [float] NULL,
  [PRGIS] [float] NULL,
  [ROTM] [float] NULL,
  [RGVM] [float] NULL,
  [PSM] [float] NULL,
  [VYRM] [float] NULL,
  [NORMAM] [float] NULL,
  [KOLM] [float] NULL,
  [TUTM] [float] NULL,
  [PRMR] [float] NULL,
  [PRMIS] [float] NULL,
  [ROTD] [float] NULL,
  [RGVD] [float] NULL,
  [PSD] [float] NULL,
  [VYRD] [float] NULL,
  [NORMAD] [float] NULL,
  [KOLD] [float] NULL,
  [TUTD] [float] NULL,
  [PRDR] [float] NULL,
  [PRDIS] [float] NULL,
  [ROTU] [float] NULL,
  [RGVU] [float] NULL,
  [PSU] [float] NULL,
  [VYRU] [float] NULL,
  [NORMAU] [float] NULL,
  [KOLU] [float] NULL,
  [TUTU] [float] NULL,
  [PRUR] [float] NULL,
  [PRUIS] [float] NULL,
  [KOLEL] [float] NULL,
  [TUTEL] [float] NULL,
  [PREL] [float] NULL,
  [DATAN] [datetime] NULL,
  [DATAK] [datetime] NULL,
  [kolot] [float] NULL,
  [kolop] [float] NULL,
  [kolk] [float] NULL,
  [tutot] [float] NULL,
  [tutop] [float] NULL,
  [tutk] [float] NULL
)
ON [PRIMARY]
GO