CREATE TABLE [dbo].[dataorg] (
  [KODORG] [int] NOT NULL,
  [SYM] [float] NULL CONSTRAINT [DF_dataorg_SYM] DEFAULT (0),
  [SYMTV] [float] NULL CONSTRAINT [DF_dataorg_SYMTV] DEFAULT (0),
  [PERTO] [float] NULL CONSTRAINT [DF_dataorg_PERTO] DEFAULT (0),
  [PERHO] [float] NULL CONSTRAINT [DF_dataorg_PERHO] DEFAULT (0),
  [PGKTO] [float] NULL CONSTRAINT [DF_dataorg_PGKTO] DEFAULT (0),
  [PERTONDS] [float] NULL CONSTRAINT [DF_dataorg_PERTONDS] DEFAULT (0),
  [SYMIDX] [float] NULL CONSTRAINT [DF_dataorg_SYMIDX] DEFAULT (0),
  [NDSIDX] [float] NULL CONSTRAINT [DF_dataorg_NDSIDX] DEFAULT (0),
  [ITOG] [float] NULL CONSTRAINT [DF_dataorg_ITOG] DEFAULT (0),
  [DATAN] [datetime] NULL,
  [DATAK] [datetime] NULL,
  [PERHONDS] [float] NULL CONSTRAINT [DF_dataorg_PERHONDS] DEFAULT (0),
  [SYMNDS] [float] NULL CONSTRAINT [DF_dataorg_SYMNDS] DEFAULT (0),
  [SUMV] [float] NULL CONSTRAINT [DF_dataorg_SUMV] DEFAULT (0),
  [SUMK] [float] NULL CONSTRAINT [DF_dataorg_SUMK] DEFAULT (0),
  [SUMVNDS] [float] NULL CONSTRAINT [DF_dataorg_SUMVNDS] DEFAULT (0),
  [SUMKNDS] [float] NULL CONSTRAINT [DF_dataorg_SUMKNDS] DEFAULT (0),
  [SUMVV] [float] NULL CONSTRAINT [DF_dataorg_SUMVV] DEFAULT (0),
  [SUMKK] [float] NULL CONSTRAINT [DF_dataorg_SUMKK] DEFAULT (0),
  [PERKO] [float] NULL CONSTRAINT [DF_dataorg_PERKO] DEFAULT (0),
  [PERKONDS] [float] NULL CONSTRAINT [DF_dataorg_PERKONDS] DEFAULT (0),
  [SYMIDXV] [float] NULL CONSTRAINT [DF_dataorg_SYMIDXV] DEFAULT (0),
  [NDSIDXV] [float] NULL CONSTRAINT [DF_dataorg_NDSIDXV] DEFAULT (0),
  [SYMIDXK] [float] NULL CONSTRAINT [DF_dataorg_SYMIDXK] DEFAULT (0),
  [NDSIDXK] [float] NULL CONSTRAINT [DF_dataorg_NDSIDXK] DEFAULT (0),
  [PKYBVO] [float] NULL CONSTRAINT [DF_dataorg_PKYBVO] DEFAULT (0),
  [PKYBKO] [float] NULL CONSTRAINT [DF_dataorg_PKYBKO] DEFAULT (0),
  [ITOGV] [float] NULL CONSTRAINT [DF_dataorg_ITOGV] DEFAULT (0),
  [ITOGK] [float] NULL CONSTRAINT [DF_dataorg_ITOGK] DEFAULT (0),
  [sumgv] [float] NULL CONSTRAINT [DF_dataorg_sumgv] DEFAULT (0),
  [symgvnds] [float] NULL CONSTRAINT [DF_dataorg_symgvnds] DEFAULT (0),
  [symgvs] [float] NULL CONSTRAINT [DF_dataorg_symgvs] DEFAULT (0),
  [gkot] [float] NULL CONSTRAINT [DF_dataorg_gkot] DEFAULT (0),
  [gkgv] [float] NULL CONSTRAINT [DF_dataorg_gkgv] DEFAULT (0),
  [pergv] [float] NULL CONSTRAINT [DF_dataorg_pergv] DEFAULT (0),
  [pergvnds] [float] NULL CONSTRAINT [DF_dataorg_pergvnds] DEFAULT (0),
  [pgkvo] [float] NULL CONSTRAINT [DF_dataorg_pgkvo] DEFAULT (0),
  [lsymot] [float] NULL CONSTRAINT [DF_dataorg_lsymot] DEFAULT (0),
  [lsymgv] [float] NULL CONSTRAINT [DF_dataorg_lsymgv] DEFAULT (0),
  [lgkot] [float] NULL CONSTRAINT [DF_dataorg_lgkot] DEFAULT (0),
  [lgkgv] [float] NULL CONSTRAINT [DF_dataorg_lgkgv] DEFAULT (0),
  [skybv] [float] NULL CONSTRAINT [DF_dataorg_skybv] DEFAULT (0),
  [skybk] [float] NULL CONSTRAINT [DF_dataorg_skybk] DEFAULT (0),
  [lsumv] [float] NULL CONSTRAINT [DF_dataorg_lsumv] DEFAULT (0),
  [lskybv] [float] NULL CONSTRAINT [DF_dataorg_lskybv] DEFAULT (0),
  [lsumk] [float] NULL CONSTRAINT [DF_dataorg_lsumk] DEFAULT (0),
  [lskybk] [float] NULL CONSTRAINT [DF_dataorg_lskybk] DEFAULT (0),
  [SUMG] [float] NULL CONSTRAINT [DF_dataorg_SUMG] DEFAULT (0),
  [SUMGNDS] [float] NULL CONSTRAINT [DF_dataorg_SUMGNDS] DEFAULT (0),
  [SUMGG] [float] NULL CONSTRAINT [DF_dataorg_SUMGG] DEFAULT (0),
  [PERGO] [float] NULL CONSTRAINT [DF_dataorg_PERGO] DEFAULT (0),
  [PERGONDS] [float] NULL CONSTRAINT [DF_dataorg_PERGONDS] DEFAULT (0),
  [SYMIDXG] [float] NULL CONSTRAINT [DF_dataorg_SYMIDXG] DEFAULT (0),
  [NDSIDXG] [float] NULL CONSTRAINT [DF_dataorg_NDSIDXG] DEFAULT (0),
  [PKYBGO] [float] NULL CONSTRAINT [DF_dataorg_PKYBGO] DEFAULT (0),
  [ITOGG] [float] NULL CONSTRAINT [DF_dataorg_ITOGG] DEFAULT (0),
  [skybg] [float] NULL CONSTRAINT [DF_dataorg_skybg] DEFAULT (0),
  [lsumg] [float] NULL CONSTRAINT [DF_dataorg_lsumg] DEFAULT (0),
  [lskybg] [float] NULL CONSTRAINT [DF_dataorg_lskybg] DEFAULT (0)
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[dataorg] WITH NOCHECK
  ADD CONSTRAINT [FK_dataorg_org] FOREIGN KEY ([KODORG]) REFERENCES [dbo].[org] ([kodorg]) ON DELETE CASCADE ON UPDATE CASCADE
GO