CREATE TABLE [dbo].[arh_dataobekt] (
  [kodobk] [int] NOT NULL,
  [GKT] [float] NULL,
  [GKV] [float] NULL,
  [ST] [int] NULL,
  [SV] [int] NULL,
  [SYMT] [float] NULL,
  [SYMV] [float] NULL,
  [PERT] [float] NULL,
  [PERV] [float] NULL,
  [PGKT] [float] NULL,
  [PGKV] [float] NULL,
  [SYMK] [float] NULL,
  [SYMGV] [float] NULL,
  [TVN] [float] NULL,
  [KDO] [float] NULL,
  [TS] [float] NULL,
  [DGV] [float] NULL,
  [TGV] [float] NULL,
  [DATAN] [datetime] NULL,
  [DATAK] [datetime] NULL,
  [symtnds] [float] NULL,
  [symvnds] [float] NULL,
  [rastarift] [float] NULL,
  [rastarifv] [float] NULL,
  [KCO] [float] NULL,
  [kybv] [float] NULL,
  [kybk] [float] NULL,
  [symh] [float] NULL,
  [symkk] [float] NULL,
  [symhnds] [float] NULL,
  [symknds] [float] NULL,
  [symhs] [float] NULL,
  [symks] [float] NULL,
  [perh] [float] NULL,
  [perk] [float] NULL,
  [pkybv] [float] NULL,
  [pkybk] [float] NULL,
  [rastarifk] [float] NULL,
  [pertnds] [float] NULL,
  [pervnds] [float] NULL,
  [perhnds] [float] NULL,
  [perknds] [float] NULL,
  [lsymt] [float] NULL,
  [lgkt] [float] NULL,
  [lsymv] [float] NULL,
  [lgkv] [float] NULL,
  [lsymh] [float] NULL,
  [lkybv] [float] NULL,
  [lsymkk] [float] NULL,
  [lkybk] [float] NULL,
  [pt] [int] NULL,
  [pv] [int] NULL,
  [rastarifg] [float] NULL CONSTRAINT [DF_arh_dataobekt_rastarifg] DEFAULT (0),
  [kybg] [float] NULL CONSTRAINT [DF_arh_dataobekt_kybg] DEFAULT (0),
  [symg] [float] NULL CONSTRAINT [DF_arh_dataobekt_symg] DEFAULT (0),
  [symgnds] [float] NULL CONSTRAINT [DF_arh_dataobekt_symgnds] DEFAULT (0),
  [symgs] [float] NULL CONSTRAINT [DF_arh_dataobekt_symgs] DEFAULT (0),
  [perg] [float] NULL CONSTRAINT [DF_arh_dataobekt_perg] DEFAULT (0),
  [pkybg] [float] NULL CONSTRAINT [DF_arh_dataobekt_pkybg] DEFAULT (0),
  [pergnds] [float] NULL CONSTRAINT [DF_arh_dataobekt_pergnds] DEFAULT (0),
  [pg] [int] NULL,
  [lsymg] [float] NULL CONSTRAINT [DF_arh_dataobekt_lsymg] DEFAULT (0),
  [lkybg] [float] NULL CONSTRAINT [DF_arh_dataobekt_lkybg] DEFAULT (0)
)
ON [PRIMARY]
GO